#!/bin/bash
  
mpv --no-video ~/pomo-sound/start.mp3
echo ""; echo ""
date

if [[ $1 = "" ]]; then
  echo "15分作業します"
  sleep 15m 
else
  echo "${1}分作業します"
  sleep $1m
fi

mpv --no-video ~/pomo-sound/se.mp4 ~/pomo-sound/end.mp3
date
